### ISSUE TITLE
Dotnet 9.0 ApplyCompressionNegotiation error:

### ISSUE THREAD

**Issue by Simnico99** [mingyaulee/Blazor.BrowserExtension#179]
There seems to be an error when building an extension using .net 9.0 it seems to have compression issues with BackgroundWorker.js 
Here is the dotnet build error:

```
PS H:\ZirconSound\src\ZirconSound.Extension> dotnet build --configuration Release
Restore complete (0.3s)
  ZirconSound.Extension failed with 1 error(s) (5.5s)
    C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk.StaticWebAssets\targets\Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(241,5): error MSB4018:
      The "ApplyCompressionNegotiation" task failed unexpectedly.
      System.InvalidOperationException: Fingerprint for 'H:\ZirconSound\src\ZirconSound.Extension\obj\Release\net9.0\browserextension\build\BackgroundWorker.js' is not defined.
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
         at System.Linq.Enumerable.ArraySelectIterator`2.MoveNext()
         at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.ApplyCompressionNegotiation.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

Build failed with 1 error(s) in 6.5s
```

Says
'H:\ZirconSound\src\ZirconSound.Extension\obj\Release\net9.0\browserextension\build\BackgroundWorker.js' is not defined.

I've checked and it does exist in the folder.

**Comment by mingyaulee** [comment]
Thanks for raising this, .Net 9 is not officially supported by this project yet. I will be looking into it when I get more free time.

**Comment by datvm** [comment]
I have just encountered this issue too. Seem to be .NET 9 only (kinda sucks because I plan to skip .NET 9).

The workaround is to add a `global.json` file:

```json
{
    "sdk": {
        "version": "8.0.404"
    }
}
```

**Comment by salty-flower** [comment]
As the error message says, fingerprint wasn't defined, so I played around a bit and was able to get it compile. However, after that the output wasn't fully working. I'm just pasting what I tried and hopefully this could help someone.

Steps:
1. Build with original setup until you see the error as main thread
2. Find `Blazor.BrowserExtension.Config.targets`. For me it's under `~\.nuget\packages\blazor.browserextension\2.0.0\build\`. Remove the static assets registration for `browserextension.config.json`:
```xml
    <ItemGroup>
      <StaticWebAsset Include="$(_BrowserExtension_Project_IntermediateOutput_ConfigFile_FilePath)">
        <SourceType>Computed</SourceType>
        <SourceId>Blazor.BrowserExtension</SourceId>
        <ContentRoot>$(_BrowserExtension_Project_IntermediateOutput_ConfigFile_Directory)</ContentRoot>
        <BasePath>_content</BasePath>
        <RelativePath>_content/browserextension.config.json</RelativePath>
        <OriginalItemSpec>$(_BrowserExtension_Project_IntermediateOutput_ConfigFile_FilePath)</OriginalItemSpec>
        <AssetKind>All</AssetKind>
        <AssetMode>All</AssetMode>
        <AssetRole>Primary</AssetRole>
        <CopyToOutputDirectory>Never</CopyToOutputDirectory>
        <CopyToPublishDirectory>Never</CopyToPublishDirectory>
      </StaticWebAsset>
    </ItemGroup>
```
3. Add below two targets to your `.csproj`. They register `BackgroundWorker.js` and `browserextension.config.json` to static assets. (Disclaimer: I haven't thought very carefully on what's the best name, what's the best target to hook onto, what's the proper way to specify every property, etc, but rather just want to get it work first)
```xml

  <Target
    BeforeTargets="ResolveJsInitializerModuleStaticWebAssets"
    Name="ResolveBuildBrowserExtensionBackgroundWorkerStaticWebAssets"
  >
    <DefineStaticWebAssets
      AssetKind="Build"
      AssetMergeSource="$(StaticWebAssetMergeTarget)"
      BasePath="$(StaticWebAssetBasePath)"
      CandidateAssets="$(IntermediateOutputPath)browserextension\build\BackgroundWorker.js"
      ContentRoot="$(OutputPath)wwwroot\"
      CopyToOutputDirectory="Always"
      RelativePathPattern="content\BackgroundWorker.js"
      SourceId="$(PackageId)"
      SourceType="Computed"
    >
      <Output
        ItemName="_BrowserExtensionBackgroundWorkerBuildStaticWebAsset"
        TaskParameter="Assets"
      />
    </DefineStaticWebAssets>

    <DefineStaticWebAssetEndpoints
      CandidateAssets="@(_BrowserExtensionBackgroundWorkerBuildStaticWebAsset)"
      ContentTypeMappings="@(StaticWebAssetContentTypeMapping)"
      ExistingEndpoints="@(StaticWebAssetEndpoint)"
    >
      <Output
        ItemName="_BrowserExtensionBackgroundWorkerBuildStaticWebAssetEndpoint"
        TaskParameter="Endpoints"
      />
    </DefineStaticWebAssetEndpoints>

    <ItemGroup>
      <StaticWebAsset
        Include="@(_BrowserExtensionBackgroundWorkerBuildStaticWebAsset)"
      />
      <StaticWebAssetEndpoint
        Include="@(_BrowserExtensionBackgroundWorkerBuildStaticWebAssetEndpoint)"
      />
    </ItemGroup>

    <ItemGroup>
      <StaticWebAssetFingerprintPattern
        Include="GeneratedJs"
        Pattern="BackgroundWorker.js"
      />
      <_JSModuleStaticWebAsset
        Include="@(_BrowserExtensionBackgroundWorkerBuildStaticWebAsset)"
      />
    </ItemGroup>
  </Target>

  <Target
    BeforeTargets="ResolveBuildBrowserExtensionBackgroundWorkerStaticWebAssets"
    Name="ResolveBuildBrowserExtensionConfigStaticWebAssets"
  >
    <DefineStaticWebAssets
      AssetKind="Build"
      AssetMergeSource="$(StaticWebAssetMergeTarget)"
      BasePath="$(StaticWebAssetBasePath)"
      CandidateAssets="$(IntermediateOutputPath)browserextension\build\browserextension.config.json"
      ContentRoot="$(OutputPath)wwwroot\"
      CopyToOutputDirectory="Always"
      RelativePathPattern="browserextension.config.json"
      SourceId="$(PackageId)"
      SourceType="Computed"
    >
      <Output
        ItemName="_BrowserExtensionConfigBuildStaticWebAsset"
        TaskParameter="Assets"
      />
    </DefineStaticWebAssets>

    <DefineStaticWebAssetEndpoints
      CandidateAssets="@(_BrowserExtensionConfigBuildStaticWebAsset)"
      ContentTypeMappings="@(StaticWebAssetContentTypeMapping)"
      ExistingEndpoints="@(StaticWebAssetEndpoint)"
    >
      <Output
        ItemName="_BrowserExtensionConfigBuildStaticWebAssetEndpoint"
        TaskParameter="Endpoints"
      />
    </DefineStaticWebAssetEndpoints>

    <ItemGroup>
      <StaticWebAsset Include="@(_BrowserExtensionConfigBuildStaticWebAsset)" />
      <StaticWebAssetEndpoint
        Include="@(_BrowserExtensionConfigBuildStaticWebAssetEndpoint)"
      />
    </ItemGroup>

    <ItemGroup>
      <StaticWebAssetFingerprintPattern
        Include="Another"
        Pattern="browserextension.config.json"
      />
      <_JSModuleStaticWebAsset
        Include="@(_BrowserExtensionConfigBuildStaticWebAsset)"
      />
    </ItemGroup>
  </Target>
```
Tip: if you see below error, delete`obj` and `bin` folders, restore the original `.targets` and your `.csproj` and build again. That would fail with the same error as the main thread, but gives the `project.assets.json`.
>      C:\Program Files\dotnet\sdk\9.0.100\Sdks\Microsoft.NET.Sdk\targets\Microsoft.PackageDependencyResolution.targets(266,5): error NETSDK1004:
>       Assets file '$(ProjectDir)\
>             $(ProjectDir)\obj\project.assets.json
>       ' not found. Run a NuGet package restore to generate this file.
4. Now the dotnet compilation should succeed and you'll see `bin\Debug\net9.0\browserextension` folder. But you won't be able to load it directly because file wasn't fully copied yet
```json
    "service_worker": "content/BackgroundWorker.js",
```
Just manually put there or use MSBuild:
```xml
  <Target AfterTargets="Build" Name="CopyGeneratedFile">
    <Copy
      DestinationFiles="$(ProjectDir)bin\Debug\net9.0\browserextension\BackgroundWorker.js"
      SourceFiles="$(ProjectDir)obj\Debug\net9.0\browserextension\build\BackgroundWorker.js"
    />
    <Copy
      DestinationFiles="$(ProjectDir)bin\Debug\net9.0\browserextension\content\browserextension.config.json"
      SourceFiles="$(ProjectDir)obj\Debug\net9.0\browserextension\build\browserextension.config.json"
    />
  </Target>
```

That's it and it should be loadable! But it doesn't work for me - at `framework/blazor.webassembly.js:2872 (anonymous function)`,
> Uncaught (in promise) Error: Failed to start platform. Reason: TypeError: Cannot read properties of undefined (reading 'withModuleConfig')

**Comment by bradleyables22** [comment]
yup can confirm --force on the global.json does solve this. i am skipping .net 9 so alll good by me.

**Comment by SongPing** [comment]
Any news about running .net 9.0 ?

**Comment by mingyaulee** [comment]
Not yet, I am still looking into it.

**Comment by mingyaulee** [comment]
This has been fixed in `v2.0.2`
