### ISSUE TITLE
[Content] 01_01_QuickStart.md

### ISSUE THREAD

**Issue by unmade-spangle** [mingyaulee/Blazor.BrowserExtension#185]
mac~ % dotnet new browserext --name MyBlazorExtension
The template "Browser extension with Blazor WebAssembly" was created successfully.

mac ~ % cd MyBlazorExtension
mac MyBlazorExtension % dotnet build
Restore complete (0.4s)
  MyBlazorExtension failed with 1 error(s) and 1 warning(s) (0.8s)
    /Users/user/MyBlazorExtension/obj/Debug/net8.0/Microsoft.CodeAnalysis.Razor.Compiler/Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator/App_razor.g.cs(105,55): warning CS0618: 'Router.PreferExactMatches' is obsolete: 'This property is obsolete and configuring it has not effect.'
    /usr/local/share/dotnet/sdk/9.0.101/Sdks/Microsoft.NET.Sdk.StaticWebAssets/targets/Microsoft.NET.Sdk.StaticWebAssets.Compression.targets(284,5): error MSB4018: 
      The "DiscoverPrecompressedAssets" task failed unexpectedly.
      System.InvalidOperationException: Fingerprint for '/Users/user/MyBlazorExtension/obj/Debug/net8.0/browserextension/build/Back
      groundWorker.js' is not defined.
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.Validate()
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.StaticWebAsset.FromTaskItem(ITaskItem item)
         at System.Linq.Enumerable.ArraySelectIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
         at System.Linq.Enumerable.ArraySelectIterator`2.ToArray()
         at Microsoft.AspNetCore.StaticWebAssets.Tasks.DiscoverPrecompressedAssets.Execute()
         at Microsoft.Build.BackEnd.TaskExecutionHost.Execute()
         at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(TaskExecutionHost taskExecutionHost, TaskLoggingContext taskLog
      gingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)

Build failed with 1 error(s) and 1 warning(s) in 1.5s
user@mac MyBlazorExtension % 

your template does not work.

**Comment by mingyaulee** [comment]
There is an existing issue #179, .Net 9 is not officially supported by this package yet. Workaround is to use .Net 8 SDK with `global.json`.
